name: ci
on:
  push:

env:
  HUSKY: 0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          nvm install
          echo "${NVM_BIN}" >> $GITHUB_PATH
        shell: bash --login {0}
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.1
          run_install: true

      - name: Run check
        run: pnpm check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          nvm install
          echo "${NVM_BIN}" >> $GITHUB_PATH
        shell: bash --login {0}
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.1
          run_install: true

      - name: Run check
        run: pnpm build

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - check
      - build
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker --quiet

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest

      - run: |
          gcloud run deploy api \
            --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --platform managed
